baseURL = "https://geofpwhite.github.io/cube-site/"
languageCode = 'en-us'
title = 'Creating a cube using the ansipixels library'
theme ='github.com/adityatelange/hugo-PaperMod'
[params]
mainSections = ["home"]

[caches]
  [caches.images]
    dir = ':cacheDir/images'