baseURL = "https://geofpwhite.github.io/cube-site/"
languageCode = 'en-us'
title = 'Creating a cube using the ansipixels library'
theme ='github.com/adityatelange/hugo-PaperMod'
[params]
mainSections = ["home"]

[module]
    [[module.imports]]
        path = "github.com/adityatelange/hugo-PaperMod"
        disable=false
        theme="hugo-PaperMod"